[tool.poetry]
name = "hw"
version = "0.1.0"
description = ""
authors = ["Дмитрий Захаров <dzakharov@astralinux.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
