apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw02-deployment
  labels:
    app: hw02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw02
  template:
    metadata:
      labels:
        app: hw02
    spec:
      containers:
      - name: hw02
        image: toolen/hw02:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 60