apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw02-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "arch.homework"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: hw02-service
            port:
              number: 80
